---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "mbialon"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "mbialon"

  - directory: /infra
    package-ecosystem: terraform
    schedule:
      interval: "weekly"
    reviewers:
      - "mbialon"
